name: stylegan2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - click=8.0.4
  - ninja=1.12.1
  - numpy=1.21.5
  - pip=22.3.1
  - python=3.7.1
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - requests=2.28.1
  - tqdm=4.64.1
  - pip:
      - imageio==2.31.2
      - imageio-ffmpeg==0.5.1
      - pillow==8.4.0
      - pyspng==0.1.2
